
services:
  # OWASP ZAP - Web Application Security Scanner
  zap:
    image: zaproxy/zap-stable:latest
    container_name: prostaff-zap
    ports:
      - "8087:8080"      # ZAP Proxy
      - "8097:8090"      # ZAP API
    volumes:
      - ./zap:/zap/wrk:rw
      - ./zap/reports:/zap/reports:rw
      - ./zap/scripts:/zap/scripts:ro
    networks:
      - security-net
    command: zap-webswing.sh
    environment:
      - ZAP_PORT=8080
      - ZAPROXY_SKIP_AUTHENTICATION=true

  # OWASP Dependency Check - Scan for vulnerable dependencies
  dependency-check:
    image: owasp/dependency-check:latest
    container_name: prostaff-dependency-check
    volumes:
      - ../:/src:ro
      - ./reports/dependency-check:/report:rw
      - ~/.m2/repository:/usr/share/dependency-check/data:rw
    networks:
      - security-net
    command: ["--scan", "/src", "--format", "ALL", "--project", "ProStaff API", "--out", "/report"]

  # Trivy - Container & Filesystem vulnerability scanner
  trivy:
    image: aquasec/trivy:latest
    container_name: prostaff-trivy
    volumes:
      - ../:/app:ro
      - ./reports/trivy:/reports:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - security-net
    entrypoint: []
    command: ["sleep", "infinity"]

  # Brakeman - Rails security scanner
  brakeman:
    image: presidentbeef/brakeman:latest
    container_name: prostaff-brakeman
    volumes:
      - ../:/app:ro
      - ./reports/brakeman:/reports:rw
    networks:
      - security-net
    working_dir: /app
    command: ["--rails7", "--output", "/reports/brakeman-report.html", "--format", "html", "--summary"]

  # Semgrep - Static analysis security tool
  semgrep:
    image: returntocorp/semgrep:latest
    container_name: prostaff-semgrep
    volumes:
      - ../:/src:ro
      - ./reports/semgrep:/reports:rw
    networks:
      - security-net
    working_dir: /src
    entrypoint: []
    command: ["sleep", "infinity"]

  # Nuclei - Fast vulnerability scanner
  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: prostaff-nuclei
    volumes:
      - ./nuclei-templates:/templates:ro
      - ./reports/nuclei:/reports:rw
    networks:
      - security-net
    command: ["sleep", "infinity"]

networks:
  security-net:
    driver: bridge
