version: '3.8'

services:
  # OWASP ZAP - Web Application Security Scanner
  zap:
    image: owasp/zap2docker-stable:latest
    container_name: prostaff-zap
    user: zap
    ports:
      - "8080:8080"      # ZAP Proxy
      - "8090:8090"      # ZAP API
    volumes:
      - ./zap:/zap/wrk:rw
      - ./zap/reports:/zap/reports:rw
      - ./zap/scripts:/zap/scripts:ro
    networks:
      - security-net
    command: zap-webswing.sh
    environment:
      - ZAP_PORT=8080

  # OWASP Dependency Check - Scan for vulnerable dependencies
  dependency-check:
    image: owasp/dependency-check:latest
    container_name: prostaff-dependency-check
    volumes:
      - ./:/src:ro
      - ./security_tests/reports/dependency-check:/report:rw
      - ~/.m2/repository:/usr/share/dependency-check/data:rw
    networks:
      - security-net
    command: >
      --scan /src
      --format ALL
      --project "ProStaff API"
      --out /report

  # Trivy - Container & Filesystem vulnerability scanner
  trivy:
    image: aquasec/trivy:latest
    container_name: prostaff-trivy
    volumes:
      - ./:/app:ro
      - ./security_tests/reports/trivy:/reports:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - security-net
    entrypoint: []
    command: ["sleep", "infinity"]

  # Brakeman - Rails security scanner
  brakeman:
    image: presidentbeef/brakeman:latest
    container_name: prostaff-brakeman
    volumes:
      - ./:/app:ro
      - ./security_tests/reports/brakeman:/reports:rw
    networks:
      - security-net
    working_dir: /app
    command: >
      --rails7
      --output /reports/brakeman-report.html
      --format html
      --summary

  # Semgrep - Static analysis security tool
  semgrep:
    image: returntocorp/semgrep:latest
    container_name: prostaff-semgrep
    volumes:
      - ./:/src:ro
      - ./security_tests/reports/semgrep:/reports:rw
    networks:
      - security-net
    working_dir: /src
    command: >
      --config=auto
      --json
      --output=/reports/semgrep-report.json

  # Nuclei - Fast vulnerability scanner
  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: prostaff-nuclei
    volumes:
      - ./security_tests/nuclei-templates:/templates:ro
      - ./security_tests/reports/nuclei:/reports:rw
    networks:
      - security-net
    command: ["sleep", "infinity"]

networks:
  security-net:
    driver: bridge
